; Generated by Character Editor
[chara_config ptext="chara_name_area" anim="true"]

[iscript]
    f.bukatsu = '补习部';
    f.azusa_top = 18.66;
    f.azusa_left = 0.00;
    f.azusa_width = 1245;
    f.azusa_size = 1;
    f.azusa_offset_L = 3.74;
    f.azusa_offset_emo_L = 14.92;
    f.azusa_offset_emo_T = 139.90;
    f.azusa  = '梓' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.azusa_log = 'Azusa';
[endscript]
;このゲームで登場するキャラクターを宣言
;azusa
[chara_new name="azusa" jname="&f.azusa" storage="chara/azusa/azusa_body.png" logname="&f.azusa_log"]
;キャラクターの表情登録
[chara_layer name="azusa" part="halo" id="normal" zindex="1" storage="chara/azusa/azusa_halo0.png" frame_image="azusa_halo1,azusa_halo2,azusa_halo3,azusa_halo4,azusa_halo5,azusa_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="azusa" part="body" id="body" zindex="2" storage="chara/azusa/azusa_body.png"]
[chara_layer name="azusa" part="face" id="default" zindex="3" storage="chara/azusa/azusa_default.png"]
[chara_layer name="azusa" part="face" id="embarrass" zindex="3" storage="chara/azusa/azusa_embarrass.png"]
[chara_layer name="azusa" part="face" id="embarrass2" zindex="3" storage="chara/azusa/azusa_embarrass2.png"]
[chara_layer name="azusa" part="face" id="embarrassed" zindex="3" storage="chara/azusa/azusa_embarrassed.png"]
[chara_layer name="azusa" part="face" id="eyeclose" zindex="3" storage="chara/azusa/azusa_eyeclose.png"]
[chara_layer name="azusa" part="face" id="normal" zindex="3" storage="chara/azusa/azusa_normal.png"]
[chara_layer name="azusa" part="face" id="respond" zindex="3" storage="chara/azusa/azusa_respond.png"]
[chara_layer name="azusa" part="face" id="serious" zindex="3" storage="chara/azusa/azusa_serious.png"]
[chara_layer name="azusa" part="face" id="smile" zindex="3" storage="chara/azusa/azusa_smile.png"]
[chara_layer name="azusa" part="face" id="smile2" zindex="3" storage="chara/azusa/azusa_smile2.png"]
[chara_layer name="azusa" part="fronthair" id="fronthair" zindex="4" storage="chara/azusa/azusa_fronthair.png"]

[iscript]
    f.bukatsu = '补习部';
    f.hihumi_top = 87;
    f.hihumi_left = 0.00;
    f.hihumi_width = 835;
    f.hihumi_size = 1;
    f.hihumi_offset_L = 5.50;
    f.hihumi_offset_emo_L = -29.95;
    f.hihumi_offset_emo_T = 80.21;
    f.hihumi  = '日富美' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.hihumi_log = 'Hihumi';
[endscript]
;このゲームで登場するキャラクターを宣言
;hihumi
[chara_new name="hihumi" jname="&f.hihumi" storage="chara/hihumi/hihumi_body.png" logname="&f.hihumi_log"]
;キャラクターの表情登録
[chara_layer name="hihumi" part="halo" id="normal" zindex="1" storage="chara/hihumi/hihumi_halo0.png" frame_image="hihumi_halo1,hihumi_halo2,hihumi_halo3,hihumi_halo4,hihumi_halo5,hihumi_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="hihumi" part="body" id="body" zindex="2" storage="chara/hihumi/hihumi_body.png"]
[chara_layer name="hihumi" part="face" id="default" zindex="3" storage="chara/hihumi/hihumi_default.png"]
[chara_layer name="hihumi" part="face" id="embarrassed" zindex="3" storage="chara/hihumi/hihumi_embarrassed.png"]
[chara_layer name="hihumi" part="face" id="eyeclose" zindex="3" storage="chara/hihumi/hihumi_eyeclose.png"]
[chara_layer name="hihumi" part="face" id="normal" zindex="3" storage="chara/hihumi/hihumi_normal.png"]
[chara_layer name="hihumi" part="face" id="respond" zindex="3" storage="chara/hihumi/hihumi_respond.png"]
[chara_layer name="hihumi" part="face" id="serious" zindex="3" storage="chara/hihumi/hihumi_serious.png"]
[chara_layer name="hihumi" part="face" id="shout" zindex="3" storage="chara/hihumi/hihumi_shout.png"]
[chara_layer name="hihumi" part="face" id="smile" zindex="3" storage="chara/hihumi/hihumi_smile.png"]

[iscript]
    f.bukatsu = '游戏开发部';
    f.midori_top = 0.00;
    f.midori_left = 0.00;
    f.midori_width = 920;
    f.midori_size = 1;
    f.midori_offset_L = -25.63;
    f.midori_offset_emo_L = 0.00;
    f.midori_offset_emo_T = 0.00;
    f.midori  = '绿' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.midori_log = 'Midori';
[endscript]
;このゲームで登場するキャラクターを宣言
;midori
[chara_new name="midori" jname="&f.midori" storage="chara/midori/midori_body.png" logname="&f.midori_log"]
;キャラクターの表情登録
[chara_layer name="midori" part="halo" id="normal" zindex="1" storage="chara/midori/midori_halo0.png" frame_image="midori_halo1,midori_halo2,midori_halo3,midori_halo4,midori_halo5,midori_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="midori" part="body" id="body" zindex="2" storage="chara/midori/midori_body.png"]
[chara_layer name="midori" part="face" id="07" zindex="3" storage="chara/midori/midori_07.png"]
[chara_layer name="midori" part="face" id="default" zindex="3" storage="chara/midori/midori_default.png"]
[chara_layer name="midori" part="face" id="depressed" zindex="3" storage="chara/midori/midori_depressed.png"]
[chara_layer name="midori" part="face" id="embarrass" zindex="3" storage="chara/midori/midori_embarrass.png"]
[chara_layer name="midori" part="face" id="eyeclose" zindex="3" storage="chara/midori/midori_eyeclose.png"]
[chara_layer name="midori" part="face" id="respond" zindex="3" storage="chara/midori/midori_respond.png"]
[chara_layer name="midori" part="face" id="sad" zindex="3" storage="chara/midori/midori_sad.png"]
[chara_layer name="midori" part="face" id="serious" zindex="3" storage="chara/midori/midori_serious.png"]
[chara_layer name="midori" part="face" id="smile" zindex="3" storage="chara/midori/midori_smile.png"]
[chara_layer name="midori" part="fronthair" id="fronthair" zindex="4" storage="chara/midori/midori_fronthair.png"]

[iscript]
    f.bukatsu = '游戏开发部';
    f.momoi_top = 72.16;
    f.momoi_left = 0.00;
    f.momoi_width = 838;
    f.momoi_size = 1;
    f.momoi_offset_L = 88.15;
    f.momoi_offset_emo_L = 117.00;
    f.momoi_offset_emo_T = 117.00;
    f.momoi  = '桃' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.momoi_log = 'Momoi';
[endscript]
;このゲームで登場するキャラクターを宣言
;momoi
[chara_new name="momoi" jname="&f.momoi" storage="chara/momoi/momoi_body.png" logname="&f.momoi_log"]
;キャラクターの表情登録
[chara_layer name="momoi" part="halo" id="normal" zindex="1" storage="chara/momoi/momoi_halo0.png" frame_image="momoi_halo1,momoi_halo2,momoi_halo3,momoi_halo4,momoi_halo5,momoi_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="momoi" part="body" id="body" zindex="2" storage="chara/momoi/momoi_body.png"]
[chara_layer name="momoi" part="face" id="07" zindex="3" storage="chara/momoi/momoi_07.png"]
[chara_layer name="momoi" part="face" id="default" zindex="3" storage="chara/momoi/momoi_default.png"]
[chara_layer name="momoi" part="face" id="depressed" zindex="3" storage="chara/momoi/momoi_depressed.png"]
[chara_layer name="momoi" part="face" id="embarrass" zindex="3" storage="chara/momoi/momoi_embarrass.png"]
[chara_layer name="momoi" part="face" id="eyeclose" zindex="3" storage="chara/momoi/momoi_eyeclose.png"]
[chara_layer name="momoi" part="face" id="normal" zindex="3" storage="chara/momoi/momoi_normal.png"]
[chara_layer name="momoi" part="face" id="respond" zindex="3" storage="chara/momoi/momoi_respond.png"]
[chara_layer name="momoi" part="face" id="serious" zindex="3" storage="chara/momoi/momoi_serious.png"]
[chara_layer name="momoi" part="face" id="smile" zindex="3" storage="chara/momoi/momoi_smile.png"]
[chara_layer name="momoi" part="fronthair" id="fronthair" zindex="4" storage="chara/momoi/momoi_fronthair.png"]

[iscript]
    f.bukatsu = '玄武商会';
    f.reizyo_top = 25.66;
    f.reizyo_left = 0.00;
    f.reizyo_width = 572;
    f.reizyo_size = 1;
    f.reizyo_offset_L = -36.87;
    f.reizyo_offset_emo_L = -19.24;
    f.reizyo_offset_emo_T = 57.73;
    f.reizyo  = '丽情' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.reizyo_log = 'Reizyo';
[endscript]
;このゲームで登場するキャラクターを宣言
;reizyo
[chara_new name="reizyo" jname="&f.reizyo" storage="chara/reizyo/reizyo_body.png" logname="&f.reizyo_log"]
;キャラクターの表情登録
[chara_layer name="reizyo" part="halo" id="normal" zindex="1" storage="chara/reizyo/reizyo_halo0.png" frame_image="reizyo_halo1,reizyo_halo2,reizyo_halo3,reizyo_halo4,reizyo_halo5,reizyo_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="reizyo" part="body" id="body" zindex="2" storage="chara/reizyo/reizyo_body.png"]
[chara_layer name="reizyo" part="face" id="default" zindex="3" storage="chara/reizyo/reizyo_default.png"]
[chara_layer name="reizyo" part="face" id="depressed" zindex="3" storage="chara/reizyo/reizyo_depressed.png"]
[chara_layer name="reizyo" part="face" id="embarrassed" zindex="3" storage="chara/reizyo/reizyo_embarrassed.png"]
[chara_layer name="reizyo" part="face" id="etc1" zindex="3" storage="chara/reizyo/reizyo_etc1.png"]
[chara_layer name="reizyo" part="face" id="etc10" zindex="3" storage="chara/reizyo/reizyo_etc10.png"]
[chara_layer name="reizyo" part="face" id="etc11" zindex="3" storage="chara/reizyo/reizyo_etc11.png"]
[chara_layer name="reizyo" part="face" id="etc12" zindex="3" storage="chara/reizyo/reizyo_etc12.png"]
[chara_layer name="reizyo" part="face" id="etc2" zindex="3" storage="chara/reizyo/reizyo_etc2.png"]
[chara_layer name="reizyo" part="face" id="etc3" zindex="3" storage="chara/reizyo/reizyo_etc3.png"]
[chara_layer name="reizyo" part="face" id="etc4" zindex="3" storage="chara/reizyo/reizyo_etc4.png"]
[chara_layer name="reizyo" part="face" id="etc5" zindex="3" storage="chara/reizyo/reizyo_etc5.png"]
[chara_layer name="reizyo" part="face" id="etc6" zindex="3" storage="chara/reizyo/reizyo_etc6.png"]
[chara_layer name="reizyo" part="face" id="etc7" zindex="3" storage="chara/reizyo/reizyo_etc7.png"]
[chara_layer name="reizyo" part="face" id="etc8" zindex="3" storage="chara/reizyo/reizyo_etc8.png"]
[chara_layer name="reizyo" part="face" id="etc9" zindex="3" storage="chara/reizyo/reizyo_etc9.png"]
[chara_layer name="reizyo" part="face" id="eyeclose" zindex="3" storage="chara/reizyo/reizyo_eyeclose.png"]
[chara_layer name="reizyo" part="face" id="normal" zindex="3" storage="chara/reizyo/reizyo_normal.png"]
[chara_layer name="reizyo" part="face" id="respond" zindex="3" storage="chara/reizyo/reizyo_respond.png"]
[chara_layer name="reizyo" part="face" id="serious" zindex="3" storage="chara/reizyo/reizyo_serious.png"]
[chara_layer name="reizyo" part="face" id="smile" zindex="3" storage="chara/reizyo/reizyo_smile.png"]
