; Generated by Character Editor
[chara_config ptext="chara_name_area" anim="true"]

[iscript]
    f.bukatsu = '玄龙门';
    f.mina_top = 0.00;
    f.mina_left = 0.00;
    f.mina_width = 920;
    f.mina_size = 1;
    f.mina_offset_L = 0.00;
    f.mina_offset_emo_L = 22.45;
    f.mina_offset_emo_T = 35.28;
    f.mina  = '南' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.mina_log = 'Mina';
[endscript]
;このゲームで登場するキャラクターを宣言
;mina
[chara_new name="mina" jname="&f.mina" storage="chara/mina/mina_body.png" logname="&f.mina_log"]
;キャラクターの表情登録
[chara_layer name="mina" part="halo" id="normal" zindex="1" storage="chara/mina/mina_halo0.png" frame_image="mina_halo1,mina_halo2,mina_halo3,mina_halo4,mina_halo5,mina_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="mina" part="body" id="body" zindex="2" storage="chara/mina/mina_body.png"]
[chara_layer name="mina" part="glasses" id="glasses" zindex="6" storage="chara/mina/mina_glasses.png"]
[chara_layer name="mina" part="face" id="07" zindex="3" storage="chara/mina/mina_07.png"]
[chara_layer name="mina" part="face" id="08" zindex="3" storage="chara/mina/mina_08.png"]
[chara_layer name="mina" part="face" id="09" zindex="3" storage="chara/mina/mina_09.png"]
[chara_layer name="mina" part="face" id="10" zindex="3" storage="chara/mina/mina_10.png"]
[chara_layer name="mina" part="face" id="11" zindex="3" storage="chara/mina/mina_11.png"]
[chara_layer name="mina" part="face" id="12" zindex="3" storage="chara/mina/mina_12.png"]
[chara_layer name="mina" part="face" id="13" zindex="3" storage="chara/mina/mina_13.png"]
[chara_layer name="mina" part="face" id="14" zindex="3" storage="chara/mina/mina_14.png"]
[chara_layer name="mina" part="face" id="15" zindex="3" storage="chara/mina/mina_15.png"]
[chara_layer name="mina" part="face" id="16" zindex="3" storage="chara/mina/mina_16.png"]
[chara_layer name="mina" part="face" id="default" zindex="3" storage="chara/mina/mina_default.png"]
[chara_layer name="mina" part="face" id="depressed" zindex="3" storage="chara/mina/mina_depressed.png"]
[chara_layer name="mina" part="face" id="embarrassed" zindex="3" storage="chara/mina/mina_embarrassed.png"]
[chara_layer name="mina" part="face" id="eyeclose" zindex="3" storage="chara/mina/mina_eyeclose.png"]
[chara_layer name="mina" part="face" id="glasses_off" zindex="3" storage="chara/mina/mina_glasses_off.png"]
[chara_layer name="mina" part="face" id="normal" zindex="3" storage="chara/mina/mina_normal.png"]
[chara_layer name="mina" part="face" id="respond" zindex="3" storage="chara/mina/mina_respond.png"]
[chara_layer name="mina" part="face" id="serious" zindex="3" storage="chara/mina/mina_serious.png"]
[chara_layer name="mina" part="face" id="smile" zindex="3" storage="chara/mina/mina_smile.png"]

[iscript]
    f.bukatsu = 'RABBIT小队';
    f.miyako_top = 56.11;
    f.miyako_left = 0.00;
    f.miyako_width = 630;
    f.miyako_size = 1;
    f.miyako_offset_L = -12.81;
    f.miyako_offset_emo_L = 0.00;
    f.miyako_offset_emo_T = 0.00;
    f.miyako  = '宫子' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.miyako_log = 'Miyako';
[endscript]
;このゲームで登場するキャラクターを宣言
;miyako
[chara_new name="miyako" jname="&f.miyako" storage="chara/miyako/miyako_body.png" logname="&f.miyako_log"]
;キャラクターの表情登録
[chara_layer name="miyako" part="halo" id="normal" zindex="1" storage="chara/miyako/miyako_halo0.png" frame_image="miyako_halo1,miyako_halo2,miyako_halo3,miyako_halo4,miyako_halo5,miyako_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="miyako" part="body" id="body" zindex="2" storage="chara/miyako/miyako_body.png"]
[chara_layer name="miyako" part="face" id="07" zindex="3" storage="chara/miyako/miyako_07.png"]
[chara_layer name="miyako" part="face" id="08" zindex="3" storage="chara/miyako/miyako_08.png"]
[chara_layer name="miyako" part="face" id="09" zindex="3" storage="chara/miyako/miyako_09.png"]
[chara_layer name="miyako" part="face" id="10" zindex="3" storage="chara/miyako/miyako_10.png"]
[chara_layer name="miyako" part="face" id="default" zindex="3" storage="chara/miyako/miyako_default.png"]
[chara_layer name="miyako" part="face" id="depressed" zindex="3" storage="chara/miyako/miyako_depressed.png"]
[chara_layer name="miyako" part="face" id="embarrass" zindex="3" storage="chara/miyako/miyako_embarrass.png"]
[chara_layer name="miyako" part="face" id="eyeclose" zindex="3" storage="chara/miyako/miyako_eyeclose.png"]
[chara_layer name="miyako" part="face" id="normal" zindex="3" storage="chara/miyako/miyako_normal.png"]
[chara_layer name="miyako" part="face" id="respond" zindex="3" storage="chara/miyako/miyako_respond.png"]
[chara_layer name="miyako" part="face" id="serious" zindex="3" storage="chara/miyako/miyako_serious.png"]
[chara_layer name="miyako" part="face" id="smile" zindex="3" storage="chara/miyako/miyako_smile.png"]
[chara_layer name="miyako" part="fronthair" id="fronthair" zindex="4" storage="chara/miyako/miyako_fronthair.png"]

[iscript]
    f.bukatsu = 'RABBIT小队';
    f.miyu_top = 86.60;
    f.miyu_left = 0.00;
    f.miyu_width = 762;
    f.miyu_size = 1;
    f.miyu_offset_L = -44.85;
    f.miyu_offset_emo_L = 0.00;
    f.miyu_offset_emo_T = 0.00;
    f.miyu  = '美游' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.miyu_log = 'Miyu';
[endscript]
;このゲームで登場するキャラクターを宣言
;miyu
[chara_new name="miyu" jname="&f.miyu" storage="chara/miyu/miyu_body.png" logname="&f.miyu_log"]
;キャラクターの表情登録
[chara_layer name="miyu" part="halo" id="normal" zindex="1" storage="chara/miyu/miyu_halo0.png" frame_image="miyu_halo1,miyu_halo2,miyu_halo3,miyu_halo4,miyu_halo5,miyu_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="miyu" part="body" id="body" zindex="2" storage="chara/miyu/miyu_body.png"]
[chara_layer name="miyu" part="face" id="07" zindex="3" storage="chara/miyu/miyu_07.png"]
[chara_layer name="miyu" part="face" id="08" zindex="3" storage="chara/miyu/miyu_08.png"]
[chara_layer name="miyu" part="face" id="09" zindex="3" storage="chara/miyu/miyu_09.png"]
[chara_layer name="miyu" part="face" id="11" zindex="3" storage="chara/miyu/miyu_11.png"]
[chara_layer name="miyu" part="face" id="12" zindex="3" storage="chara/miyu/miyu_12.png"]
[chara_layer name="miyu" part="face" id="default" zindex="3" storage="chara/miyu/miyu_default.png"]
[chara_layer name="miyu" part="face" id="depressed" zindex="3" storage="chara/miyu/miyu_depressed.png"]
[chara_layer name="miyu" part="face" id="embarrass" zindex="3" storage="chara/miyu/miyu_embarrass.png"]
[chara_layer name="miyu" part="face" id="eyeclose" zindex="3" storage="chara/miyu/miyu_eyeclose.png"]
[chara_layer name="miyu" part="face" id="face" zindex="3" storage="chara/miyu/miyu_face.png"]
[chara_layer name="miyu" part="face" id="normal" zindex="3" storage="chara/miyu/miyu_normal.png"]
[chara_layer name="miyu" part="face" id="respond" zindex="3" storage="chara/miyu/miyu_respond.png"]
[chara_layer name="miyu" part="face" id="serious" zindex="3" storage="chara/miyu/miyu_serious.png"]
[chara_layer name="miyu" part="face" id="smile" zindex="3" storage="chara/miyu/miyu_smile.png"]
[chara_layer name="miyu" part="fronthair" id="fronthair" zindex="4" storage="chara/miyu/miyu_fronthair.png"]

[iscript]
    f.bukatsu = 'RABBIT小队';
    f.moe_top = 136.30;
    f.moe_left = 0.00;
    f.moe_width = 630;
    f.moe_size = 1;
    f.moe_offset_L = -17.64;
    f.moe_offset_emo_L = 0.00;
    f.moe_offset_emo_T = 0.00;
    f.moe  = '萌绘' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.moe_log = 'Moe';
[endscript]
;このゲームで登場するキャラクターを宣言
;moe
[chara_new name="moe" jname="&f.moe" storage="chara/moe/moe_body.png" logname="&f.moe_log"]
;キャラクターの表情登録
[chara_layer name="moe" part="halo" id="normal" zindex="1" storage="chara/moe/moe_halo0.png" frame_image="moe_halo1,moe_halo2,moe_halo3,moe_halo4,moe_halo5,moe_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="moe" part="body" id="body" zindex="2" storage="chara/moe/moe_body.png"]
[chara_layer name="moe" part="glasses" id="glasses" zindex="6" storage="chara/moe/moe_glasses.png"]
[chara_layer name="moe" part="face" id="07" zindex="3" storage="chara/moe/moe_07.png"]
[chara_layer name="moe" part="face" id="08" zindex="3" storage="chara/moe/moe_08.png"]
[chara_layer name="moe" part="face" id="09" zindex="3" storage="chara/moe/moe_09.png"]
[chara_layer name="moe" part="face" id="10" zindex="3" storage="chara/moe/moe_10.png"]
[chara_layer name="moe" part="face" id="11" zindex="3" storage="chara/moe/moe_11.png"]
[chara_layer name="moe" part="face" id="12" zindex="3" storage="chara/moe/moe_12.png"]
[chara_layer name="moe" part="face" id="13" zindex="3" storage="chara/moe/moe_13.png"]
[chara_layer name="moe" part="face" id="14" zindex="3" storage="chara/moe/moe_14.png"]
[chara_layer name="moe" part="face" id="15" zindex="3" storage="chara/moe/moe_15.png"]
[chara_layer name="moe" part="face" id="16" zindex="3" storage="chara/moe/moe_16.png"]
[chara_layer name="moe" part="face" id="17" zindex="3" storage="chara/moe/moe_17.png"]
[chara_layer name="moe" part="face" id="18" zindex="3" storage="chara/moe/moe_18.png"]
[chara_layer name="moe" part="face" id="default" zindex="3" storage="chara/moe/moe_default.png"]
[chara_layer name="moe" part="face" id="depressed" zindex="3" storage="chara/moe/moe_depressed.png"]
[chara_layer name="moe" part="face" id="embarrassed" zindex="3" storage="chara/moe/moe_embarrassed.png"]
[chara_layer name="moe" part="face" id="eyeclose" zindex="3" storage="chara/moe/moe_eyeclose.png"]
[chara_layer name="moe" part="face" id="glasses_off" zindex="3" storage="chara/moe/moe_glasses_off.png"]
[chara_layer name="moe" part="face" id="normal" zindex="3" storage="chara/moe/moe_normal.png"]
[chara_layer name="moe" part="face" id="respond" zindex="3" storage="chara/moe/moe_respond.png"]
[chara_layer name="moe" part="face" id="serious" zindex="3" storage="chara/moe/moe_serious.png"]
[chara_layer name="moe" part="face" id="smile" zindex="3" storage="chara/moe/moe_smile.png"]
[chara_layer name="moe" part="fronthair" id="fronthair" zindex="4" storage="chara/moe/moe_fronthair.png"]

[iscript]
    f.bukatsu = 'RABBIT小队';
    f.saki_top = 40.09;
    f.saki_left = 0.00;
    f.saki_width = 572;
    f.saki_size = 1;
    f.saki_offset_L = -36.83;
    f.saki_offset_emo_L = -14.43;
    f.saki_offset_emo_T = 73.76;
    f.saki  = '咲' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.saki_log = 'Saki';
[endscript]
;このゲームで登場するキャラクターを宣言
;saki
[chara_new name="saki" jname="&f.saki" storage="chara/saki/saki_body.png" logname="&f.saki_log"]
;キャラクターの表情登録
[chara_layer name="saki" part="halo" id="normal" zindex="1" storage="chara/saki/saki_halo0.png" frame_image="saki_halo1,saki_halo2,saki_halo3,saki_halo4,saki_halo5,saki_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="saki" part="body" id="body" zindex="2" storage="chara/saki/saki_body.png"]
[chara_layer name="saki" part="mask" id="mask" zindex="5" storage="chara/saki/saki_mask.png"]
[chara_layer name="saki" part="face" id="07" zindex="3" storage="chara/saki/saki_07.png"]
[chara_layer name="saki" part="face" id="08" zindex="3" storage="chara/saki/saki_08.png"]
[chara_layer name="saki" part="face" id="09" zindex="3" storage="chara/saki/saki_09.png"]
[chara_layer name="saki" part="face" id="10" zindex="3" storage="chara/saki/saki_10.png"]
[chara_layer name="saki" part="face" id="11" zindex="3" storage="chara/saki/saki_11.png"]
[chara_layer name="saki" part="face" id="12" zindex="3" storage="chara/saki/saki_12.png"]
[chara_layer name="saki" part="face" id="13" zindex="3" storage="chara/saki/saki_13.png"]
[chara_layer name="saki" part="face" id="default" zindex="3" storage="chara/saki/saki_default.png"]
[chara_layer name="saki" part="face" id="default_H" zindex="3" storage="chara/saki/saki_default_H.png"]
[chara_layer name="saki" part="face" id="depressed" zindex="3" storage="chara/saki/saki_depressed.png"]
[chara_layer name="saki" part="face" id="embarrass" zindex="3" storage="chara/saki/saki_embarrass.png"]
[chara_layer name="saki" part="face" id="eyeclose" zindex="3" storage="chara/saki/saki_eyeclose.png"]
[chara_layer name="saki" part="face" id="mask_off" zindex="3" storage="chara/saki/saki_mask_off.png"]
[chara_layer name="saki" part="face" id="normal" zindex="3" storage="chara/saki/saki_normal.png"]
[chara_layer name="saki" part="face" id="respond" zindex="3" storage="chara/saki/saki_respond.png"]
[chara_layer name="saki" part="face" id="serious" zindex="3" storage="chara/saki/saki_serious.png"]
[chara_layer name="saki" part="face" id="smile" zindex="3" storage="chara/saki/saki_smile.png"]
