; Generated by Character Editor
[chara_config ptext="chara_name_area" anim="true"]

[iscript]
    f.bukatsu = '红冬事务局';
    f.cherino_top = 122.92;
    f.cherino_left = 0.00;
    f.cherino_width = 754;
    f.cherino_size = 1;
    f.cherino_offset_L = 1.86;
    f.cherino_offset_emo_L = 16.79;
    f.cherino_offset_emo_T = 149.22;
    f.cherino  = '切里诺' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.cherino_log = 'Cherino';
[endscript]
;このゲームで登場するキャラクターを宣言
;cherino
[chara_new name="cherino" jname="&f.cherino" storage="chara/cherino/cherino_body.png" logname="&f.cherino_log"]
;キャラクターの表情登録
[chara_layer name="cherino" part="halo" id="normal" zindex="1" storage="chara/cherino/cherino_halo0.png" frame_image="cherino_halo1,cherino_halo2,cherino_halo3,cherino_halo4,cherino_halo5,cherino_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="cherino" part="body" id="body" zindex="2" storage="chara/cherino/cherino_body.png"]
[chara_layer name="cherino" part="mask" id="mask" zindex="5" storage="chara/cherino/cherino_mask.png"]
[chara_layer name="cherino" part="face" id="default" zindex="3" storage="chara/cherino/cherino_default.png"]
[chara_layer name="cherino" part="face" id="default2" zindex="3" storage="chara/cherino/cherino_default2.png"]
[chara_layer name="cherino" part="face" id="depressed" zindex="3" storage="chara/cherino/cherino_depressed.png"]
[chara_layer name="cherino" part="face" id="depressed2" zindex="3" storage="chara/cherino/cherino_depressed2.png"]
[chara_layer name="cherino" part="face" id="embarrassed" zindex="3" storage="chara/cherino/cherino_embarrassed.png"]
[chara_layer name="cherino" part="face" id="embarrassed2" zindex="3" storage="chara/cherino/cherino_embarrassed2.png"]
[chara_layer name="cherino" part="face" id="eyeclose" zindex="3" storage="chara/cherino/cherino_eyeclose.png"]
[chara_layer name="cherino" part="face" id="eyeclose2" zindex="3" storage="chara/cherino/cherino_eyeclose2.png"]
[chara_layer name="cherino" part="face" id="mask_off" zindex="3" storage="chara/cherino/cherino_mask_off.png"]
[chara_layer name="cherino" part="face" id="normal" zindex="3" storage="chara/cherino/cherino_normal.png"]
[chara_layer name="cherino" part="face" id="normal2" zindex="3" storage="chara/cherino/cherino_normal2.png"]
[chara_layer name="cherino" part="face" id="respond" zindex="3" storage="chara/cherino/cherino_respond.png"]
[chara_layer name="cherino" part="face" id="respond2" zindex="3" storage="chara/cherino/cherino_respond2.png"]
[chara_layer name="cherino" part="face" id="serious" zindex="3" storage="chara/cherino/cherino_serious.png"]
[chara_layer name="cherino" part="face" id="serious2" zindex="3" storage="chara/cherino/cherino_serious2.png"]
[chara_layer name="cherino" part="face" id="smile" zindex="3" storage="chara/cherino/cherino_smile.png"]
[chara_layer name="cherino" part="face" id="smile2" zindex="3" storage="chara/cherino/cherino_smile2.png"]

[iscript]
    f.bukatsu = '万魔殿';
    f.ibuki_top = 91.43;
    f.ibuki_left = 0.00;
    f.ibuki_width = 693;
    f.ibuki_size = 1;
    f.ibuki_offset_L = -55.09;
    f.ibuki_offset_emo_L = -11.35;
    f.ibuki_offset_emo_T = 184.86;
    f.ibuki  = '伊吹' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.ibuki_log = 'Ibuki';
[endscript]
;このゲームで登場するキャラクターを宣言
;ibuki
[chara_new name="ibuki" jname="&f.ibuki" storage="chara/ibuki/ibuki_body.png" logname="&f.ibuki_log"]
;キャラクターの表情登録
[chara_layer name="ibuki" part="halo" id="normal" zindex="1" storage="chara/ibuki/ibuki_halo0.png" frame_image="ibuki_halo1,ibuki_halo2,ibuki_halo3,ibuki_halo4,ibuki_halo5,ibuki_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="ibuki" part="body" id="body" zindex="2" storage="chara/ibuki/ibuki_body.png"]
[chara_layer name="ibuki" part="face" id="becomesulky" zindex="3" storage="chara/ibuki/ibuki_becomesulky.png"]
[chara_layer name="ibuki" part="face" id="default" zindex="3" storage="chara/ibuki/ibuki_default.png"]
[chara_layer name="ibuki" part="face" id="depressed" zindex="3" storage="chara/ibuki/ibuki_depressed.png"]
[chara_layer name="ibuki" part="face" id="embarrass" zindex="3" storage="chara/ibuki/ibuki_embarrass.png"]
[chara_layer name="ibuki" part="face" id="exciting" zindex="3" storage="chara/ibuki/ibuki_exciting.png"]
[chara_layer name="ibuki" part="face" id="eyeclose" zindex="3" storage="chara/ibuki/ibuki_eyeclose.png"]
[chara_layer name="ibuki" part="face" id="interest" zindex="3" storage="chara/ibuki/ibuki_interest.png"]
[chara_layer name="ibuki" part="face" id="normal" zindex="3" storage="chara/ibuki/ibuki_normal.png"]
[chara_layer name="ibuki" part="face" id="respond" zindex="3" storage="chara/ibuki/ibuki_respond.png"]
[chara_layer name="ibuki" part="face" id="serious" zindex="3" storage="chara/ibuki/ibuki_serious.png"]
[chara_layer name="ibuki" part="face" id="smile" zindex="3" storage="chara/ibuki/ibuki_smile.png"]

[iscript]
    f.bukatsu = '梅花园';
    f.shun_top = 10.84;
    f.shun_left = 0.00;
    f.shun_width = 628;
    f.shun_size = 1;
    f.shun_offset_L = -3.21;
    f.shun_offset_emo_L = 0.00;
    f.shun_offset_emo_T = 0.00;
    f.shun  = '瞬' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.shun_log = 'Shun';
[endscript]
;このゲームで登場するキャラクターを宣言
;shun
[chara_new name="shun" jname="&f.shun" storage="chara/shun/shun_body.png" logname="&f.shun_log"]
;キャラクターの表情登録
[chara_layer name="shun" part="halo" id="normal" zindex="1" storage="chara/shun/shun_halo0.png" frame_image="shun_halo1,shun_halo2,shun_halo3,shun_halo4,shun_halo5,shun_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="shun" part="body" id="body" zindex="2" storage="chara/shun/shun_body.png"]
[chara_layer name="shun" part="face" id="07" zindex="3" storage="chara/shun/shun_07.png"]
[chara_layer name="shun" part="face" id="beg" zindex="3" storage="chara/shun/shun_beg.png"]
[chara_layer name="shun" part="face" id="bittersmile" zindex="3" storage="chara/shun/shun_bittersmile.png"]
[chara_layer name="shun" part="face" id="default" zindex="3" storage="chara/shun/shun_default.png"]
[chara_layer name="shun" part="face" id="depressed" zindex="3" storage="chara/shun/shun_depressed.png"]
[chara_layer name="shun" part="face" id="embarrass" zindex="3" storage="chara/shun/shun_embarrass.png"]
[chara_layer name="shun" part="face" id="embarrass2" zindex="3" storage="chara/shun/shun_embarrass2.png"]
[chara_layer name="shun" part="face" id="exciting" zindex="3" storage="chara/shun/shun_exciting.png"]
[chara_layer name="shun" part="face" id="eyeclose" zindex="3" storage="chara/shun/shun_eyeclose.png"]
[chara_layer name="shun" part="face" id="normal" zindex="3" storage="chara/shun/shun_normal.png"]
[chara_layer name="shun" part="face" id="respond" zindex="3" storage="chara/shun/shun_respond.png"]
[chara_layer name="shun" part="face" id="serious" zindex="3" storage="chara/shun/shun_serious.png"]
[chara_layer name="shun" part="face" id="sigh" zindex="3" storage="chara/shun/shun_sigh.png"]
[chara_layer name="shun" part="face" id="smile" zindex="3" storage="chara/shun/shun_smile.png"]
[chara_layer name="shun" part="face" id="smile2" zindex="3" storage="chara/shun/shun_smile2.png"]
[chara_layer name="shun" part="face" id="surprised" zindex="3" storage="chara/shun/shun_surprised.png"]
[chara_layer name="shun" part="fronthair" id="fronthair" zindex="4" storage="chara/shun/shun_fronthair.png"]

[iscript]
    f.bukatsu = '梅花园';
    f.shunlin_top = 125.08;
    f.shunlin_left = 0.00;
    f.shunlin_width = 429;
    f.shunlin_size = 1;
    f.shunlin_offset_L = -99.38;
    f.shunlin_offset_emo_L = -94.61;
    f.shunlin_offset_emo_T = 206.86;
    f.shunlin  = '雪玲' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.shunlin_log = 'Shunlin';
[endscript]
;このゲームで登場するキャラクターを宣言
;shunlin
[chara_new name="shunlin" jname="&f.shunlin" storage="chara/shunlin/shunlin_body.png" logname="&f.shunlin_log"]
;キャラクターの表情登録
[chara_layer name="shunlin" part="halo" id="normal" zindex="1" storage="chara/shunlin/shunlin_halo0.png" frame_image="shunlin_halo1,shunlin_halo2,shunlin_halo3,shunlin_halo4,shunlin_halo5,shunlin_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="shunlin" part="body" id="body" zindex="2" storage="chara/shunlin/shunlin_body.png"]
[chara_layer name="shunlin" part="face" id="anger" zindex="3" storage="chara/shunlin/shunlin_anger.png"]
[chara_layer name="shunlin" part="face" id="beg1" zindex="3" storage="chara/shunlin/shunlin_beg1.png"]
[chara_layer name="shunlin" part="face" id="beg2" zindex="3" storage="chara/shunlin/shunlin_beg2.png"]
[chara_layer name="shunlin" part="face" id="beware" zindex="3" storage="chara/shunlin/shunlin_beware.png"]
[chara_layer name="shunlin" part="face" id="bittersmile" zindex="3" storage="chara/shunlin/shunlin_bittersmile.png"]
[chara_layer name="shunlin" part="face" id="blush1" zindex="3" storage="chara/shunlin/shunlin_blush1.png"]
[chara_layer name="shunlin" part="face" id="blush2" zindex="3" storage="chara/shunlin/shunlin_blush2.png"]
[chara_layer name="shunlin" part="face" id="blush3" zindex="3" storage="chara/shunlin/shunlin_blush3.png"]
[chara_layer name="shunlin" part="face" id="def" zindex="3" storage="chara/shunlin/shunlin_def.png"]
[chara_layer name="shunlin" part="face" id="depressed1" zindex="3" storage="chara/shunlin/shunlin_depressed1.png"]
[chara_layer name="shunlin" part="face" id="depressed2" zindex="3" storage="chara/shunlin/shunlin_depressed2.png"]
[chara_layer name="shunlin" part="face" id="difficult1" zindex="3" storage="chara/shunlin/shunlin_difficult1.png"]
[chara_layer name="shunlin" part="face" id="difficult2" zindex="3" storage="chara/shunlin/shunlin_difficult2.png"]
[chara_layer name="shunlin" part="face" id="difficult3" zindex="3" storage="chara/shunlin/shunlin_difficult3.png"]
[chara_layer name="shunlin" part="face" id="embarassed" zindex="3" storage="chara/shunlin/shunlin_embarassed.png"]
[chara_layer name="shunlin" part="face" id="embarassed2" zindex="3" storage="chara/shunlin/shunlin_embarassed2.png"]
[chara_layer name="shunlin" part="face" id="excuse1" zindex="3" storage="chara/shunlin/shunlin_excuse1.png"]
[chara_layer name="shunlin" part="face" id="excuse2" zindex="3" storage="chara/shunlin/shunlin_excuse2.png"]
[chara_layer name="shunlin" part="face" id="excuse3" zindex="3" storage="chara/shunlin/shunlin_excuse3.png"]
[chara_layer name="shunlin" part="face" id="eyeclose" zindex="3" storage="chara/shunlin/shunlin_eyeclose.png"]
[chara_layer name="shunlin" part="face" id="normal" zindex="3" storage="chara/shunlin/shunlin_normal.png"]
[chara_layer name="shunlin" part="face" id="relaxed1" zindex="3" storage="chara/shunlin/shunlin_relaxed1.png"]
[chara_layer name="shunlin" part="face" id="relaxed2" zindex="3" storage="chara/shunlin/shunlin_relaxed2.png"]
[chara_layer name="shunlin" part="face" id="respond" zindex="3" storage="chara/shunlin/shunlin_respond.png"]
[chara_layer name="shunlin" part="face" id="serious1" zindex="3" storage="chara/shunlin/shunlin_serious1.png"]
[chara_layer name="shunlin" part="face" id="serious2" zindex="3" storage="chara/shunlin/shunlin_serious2.png"]
[chara_layer name="shunlin" part="face" id="serious3" zindex="3" storage="chara/shunlin/shunlin_serious3.png"]
[chara_layer name="shunlin" part="face" id="shout" zindex="3" storage="chara/shunlin/shunlin_shout.png"]
[chara_layer name="shunlin" part="face" id="smile1" zindex="3" storage="chara/shunlin/shunlin_smile1.png"]
[chara_layer name="shunlin" part="face" id="smile2" zindex="3" storage="chara/shunlin/shunlin_smile2.png"]
[chara_layer name="shunlin" part="face" id="smile3" zindex="3" storage="chara/shunlin/shunlin_smile3.png"]
[chara_layer name="shunlin" part="face" id="upset1" zindex="3" storage="chara/shunlin/shunlin_upset1.png"]
[chara_layer name="shunlin" part="face" id="upset2" zindex="3" storage="chara/shunlin/shunlin_upset2.png"]
[chara_layer name="shunlin" part="face" id="upset3" zindex="3" storage="chara/shunlin/shunlin_upset3.png"]
[chara_layer name="shunlin" part="fronthair" id="fronthair" zindex="4" storage="chara/shunlin/shunlin_fronthair.png"]
