; Generated by Character Editor
[chara_config ptext="chara_name_area" anim="true"]

[iscript]
    f.bukatsu = '美食研究会';
    f.haruna_top = 9.73;
    f.haruna_left = 0.00;
    f.haruna_width = 1013;
    f.haruna_size = 1;
    f.haruna_offset_L = -89.15;
    f.haruna_offset_emo_L = -12.97;
    f.haruna_offset_emo_T = 38.92;
    f.haruna  = '晴奈' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.haruna_log = 'Haruna';
[endscript]
;このゲームで登場するキャラクターを宣言
;haruna
[chara_new name="haruna" jname="&f.haruna" storage="chara/haruna/haruna_body.png" logname="&f.haruna_log"]
;キャラクターの表情登録
[chara_layer name="haruna" part="halo" id="normal" zindex="1" storage="chara/haruna/haruna_halo0.png" frame_image="haruna_halo1,haruna_halo2,haruna_halo3,haruna_halo4,haruna_halo5,haruna_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="haruna" part="body" id="body" zindex="2" storage="chara/haruna/haruna_body.png"]
[chara_layer name="haruna" part="face" id="default" zindex="3" storage="chara/haruna/haruna_default.png"]
[chara_layer name="haruna" part="face" id="embarrassed" zindex="3" storage="chara/haruna/haruna_embarrassed.png"]
[chara_layer name="haruna" part="face" id="embarrassed2" zindex="3" storage="chara/haruna/haruna_embarrassed2.png"]
[chara_layer name="haruna" part="face" id="eyeclose" zindex="3" storage="chara/haruna/haruna_eyeclose.png"]
[chara_layer name="haruna" part="face" id="normal" zindex="3" storage="chara/haruna/haruna_normal.png"]
[chara_layer name="haruna" part="face" id="respond" zindex="3" storage="chara/haruna/haruna_respond.png"]
[chara_layer name="haruna" part="face" id="serious" zindex="3" storage="chara/haruna/haruna_serious.png"]
[chara_layer name="haruna" part="face" id="shout" zindex="3" storage="chara/haruna/haruna_shout.png"]
[chara_layer name="haruna" part="face" id="smile" zindex="3" storage="chara/haruna/haruna_smile.png"]

[iscript]
    f.bukatsu = '供餐部';
    f.juri_top = 20.16;
    f.juri_left = 0.00;
    f.juri_width = 1013;
    f.juri_size = 1;
    f.juri_offset_L = -85.87;
    f.juri_offset_emo_L = -4.86;
    f.juri_offset_emo_T = 27.57;
    f.juri  = '朱莉' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.juri_log = 'Juri';
[endscript]
;このゲームで登場するキャラクターを宣言
;juri
[chara_new name="juri" jname="&f.juri" storage="chara/juri/juri_body.png" logname="&f.juri_log"]
;キャラクターの表情登録
[chara_layer name="juri" part="halo" id="normal" zindex="1" storage="chara/juri/juri_halo0.png" frame_image="juri_halo1,juri_halo2,juri_halo3,juri_halo4,juri_halo5,juri_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="juri" part="body" id="body" zindex="2" storage="chara/juri/juri_body.png"]
[chara_layer name="juri" part="face" id="11" zindex="3" storage="chara/juri/juri_11.png"]
[chara_layer name="juri" part="face" id="default" zindex="3" storage="chara/juri/juri_default.png"]
[chara_layer name="juri" part="face" id="depressed" zindex="3" storage="chara/juri/juri_depressed.png"]
[chara_layer name="juri" part="face" id="embarrass" zindex="3" storage="chara/juri/juri_embarrass.png"]
[chara_layer name="juri" part="face" id="eyeclose" zindex="3" storage="chara/juri/juri_eyeclose.png"]
[chara_layer name="juri" part="face" id="normal" zindex="3" storage="chara/juri/juri_normal.png"]
[chara_layer name="juri" part="face" id="normal2" zindex="3" storage="chara/juri/juri_normal2.png"]
[chara_layer name="juri" part="face" id="respond" zindex="3" storage="chara/juri/juri_respond.png"]
[chara_layer name="juri" part="face" id="serious" zindex="3" storage="chara/juri/juri_serious.png"]
[chara_layer name="juri" part="face" id="shock" zindex="3" storage="chara/juri/juri_shock.png"]
[chara_layer name="juri" part="face" id="smile" zindex="3" storage="chara/juri/juri_smile.png"]
[chara_layer name="juri" part="face" id="smile2" zindex="3" storage="chara/juri/juri_smile2.png"]
[chara_layer name="juri" part="face" id="smile3" zindex="3" storage="chara/juri/juri_smile3.png"]
[chara_layer name="juri" part="face" id="status" zindex="3" storage="chara/juri/juri_status.png"]
[chara_layer name="juri" part="fronthair" id="fronthair" zindex="4" storage="chara/juri/juri_fronthair.png"]

[iscript]
    f.bukatsu = '玄武商会';
    f.rumi_top = 30.47;
    f.rumi_left = 0.00;
    f.rumi_width = 629;
    f.rumi_size = 1;
    f.rumi_offset_L = 27.25;
    f.rumi_offset_emo_L = 0.00;
    f.rumi_offset_emo_T = 0.00;
    f.rumi  = '瑠海' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.rumi_log = 'Rumi';
[endscript]
;このゲームで登場するキャラクターを宣言
;rumi
[chara_new name="rumi" jname="&f.rumi" storage="chara/rumi/rumi_body.png" logname="&f.rumi_log"]
;キャラクターの表情登録
[chara_layer name="rumi" part="halo" id="normal" zindex="1" storage="chara/rumi/rumi_halo0.png" frame_image="rumi_halo1,rumi_halo2,rumi_halo3,rumi_halo4,rumi_halo5,rumi_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="rumi" part="body" id="body" zindex="2" storage="chara/rumi/rumi_body.png"]
[chara_layer name="rumi" part="face" id="default" zindex="3" storage="chara/rumi/rumi_default.png"]
[chara_layer name="rumi" part="face" id="depressed" zindex="3" storage="chara/rumi/rumi_depressed.png"]
[chara_layer name="rumi" part="face" id="embarrassed" zindex="3" storage="chara/rumi/rumi_embarrassed.png"]
[chara_layer name="rumi" part="face" id="excited" zindex="3" storage="chara/rumi/rumi_excited.png"]
[chara_layer name="rumi" part="face" id="eyeclose" zindex="3" storage="chara/rumi/rumi_eyeclose.png"]
[chara_layer name="rumi" part="face" id="normal" zindex="3" storage="chara/rumi/rumi_normal.png"]
[chara_layer name="rumi" part="face" id="respond" zindex="3" storage="chara/rumi/rumi_respond.png"]
[chara_layer name="rumi" part="face" id="serious" zindex="3" storage="chara/rumi/rumi_serious.png"]
[chara_layer name="rumi" part="face" id="smile" zindex="3" storage="chara/rumi/rumi_smile.png"]
[chara_layer name="rumi" part="fronthair" id="fronthair" zindex="4" storage="chara/rumi/rumi_fronthair.png"]
