; Generated by Character Editor
[chara_config ptext="chara_name_area" anim="true"]

[iscript]
    f.bukatsu = '对策委员会';
    f.hoshino_top = 105.13;
    f.hoshino_left = 24.00;
    f.hoshino_width = 759;
    f.hoshino_size = 1;
    f.hoshino_offset_L = -64.81;
    f.hoshino_offset_emo_L = 17.84;
    f.hoshino_offset_emo_T = 129.73;
    f.hoshino  = '星野' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.hoshino_log = 'Hoshino';
[endscript]
;このゲームで登場するキャラクターを宣言
;hoshino
[chara_new name="hoshino" jname="&f.hoshino" storage="chara/hoshino/hoshino_body.png" logname="&f.hoshino_log"]
;キャラクターの表情登録
[chara_layer name="hoshino" part="halo" id="normal" zindex="1" storage="chara/hoshino/hoshino_halo0.png" frame_image="hoshino_halo1,hoshino_halo2,hoshino_halo3,hoshino_halo4,hoshino_halo5,hoshino_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="hoshino" part="body" id="body" zindex="2" storage="chara/hoshino/hoshino_body.png"]
[chara_layer name="hoshino" part="face" id="boring" zindex="3" storage="chara/hoshino/hoshino_boring.png"]
[chara_layer name="hoshino" part="face" id="calmsmile" zindex="3" storage="chara/hoshino/hoshino_calmsmile.png"]
[chara_layer name="hoshino" part="face" id="default" zindex="3" storage="chara/hoshino/hoshino_default.png"]
[chara_layer name="hoshino" part="face" id="difficult1" zindex="3" storage="chara/hoshino/hoshino_difficult1.png"]
[chara_layer name="hoshino" part="face" id="difficult2" zindex="3" storage="chara/hoshino/hoshino_difficult2.png"]
[chara_layer name="hoshino" part="face" id="difficult3" zindex="3" storage="chara/hoshino/hoshino_difficult3.png"]
[chara_layer name="hoshino" part="face" id="embarrassed" zindex="3" storage="chara/hoshino/hoshino_embarrassed.png"]
[chara_layer name="hoshino" part="face" id="eyeclose" zindex="3" storage="chara/hoshino/hoshino_eyeclose.png"]
[chara_layer name="hoshino" part="face" id="normal" zindex="3" storage="chara/hoshino/hoshino_normal.png"]
[chara_layer name="hoshino" part="face" id="respond" zindex="3" storage="chara/hoshino/hoshino_respond.png"]
[chara_layer name="hoshino" part="face" id="serious" zindex="3" storage="chara/hoshino/hoshino_serious.png"]
[chara_layer name="hoshino" part="face" id="shout" zindex="3" storage="chara/hoshino/hoshino_shout.png"]
[chara_layer name="hoshino" part="face" id="shout2" zindex="3" storage="chara/hoshino/hoshino_shout2.png"]
[chara_layer name="hoshino" part="face" id="shy1" zindex="3" storage="chara/hoshino/hoshino_shy1.png"]
[chara_layer name="hoshino" part="face" id="shy2" zindex="3" storage="chara/hoshino/hoshino_shy2.png"]
[chara_layer name="hoshino" part="face" id="smile" zindex="3" storage="chara/hoshino/hoshino_smile.png"]
[chara_layer name="hoshino" part="face" id="trick1" zindex="3" storage="chara/hoshino/hoshino_trick1.png"]
[chara_layer name="hoshino" part="face" id="trick2" zindex="3" storage="chara/hoshino/hoshino_trick2.png"]
[chara_layer name="hoshino" part="face" id="worry" zindex="3" storage="chara/hoshino/hoshino_worry.png"]
[chara_layer name="hoshino" part="fronthair" id="fronthair" zindex="4" storage="chara/hoshino/hoshino_fronthair.png"]

[iscript]
    f.bukatsu = '玄龙门';
    f.kisaki_top = 87.57;
    f.kisaki_left = 0.00;
    f.kisaki_width = 837;
    f.kisaki_size = 1;
    f.kisaki_offset_L = 0;
    f.kisaki_offset_emo_L = -29.00;
    f.kisaki_offset_emo_T = 53.19;
    f.kisaki  = '妃咲' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.kisaki_log = 'Kisaki';
[endscript]
;このゲームで登場するキャラクターを宣言
;kisaki
[chara_new name="kisaki" jname="&f.kisaki" storage="chara/kisaki/kisaki_body.png" logname="&f.kisaki_log"]
;キャラクターの表情登録
[chara_layer name="kisaki" part="halo" id="normal" zindex="1" storage="chara/kisaki/kisaki_halo0.png" frame_image="kisaki_halo1,kisaki_halo2,kisaki_halo3,kisaki_halo4,kisaki_halo5,kisaki_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="kisaki" part="body" id="body" zindex="2" storage="chara/kisaki/kisaki_body.png"]
[chara_layer name="kisaki" part="face" id="07" zindex="3" storage="chara/kisaki/kisaki_07.png"]
[chara_layer name="kisaki" part="face" id="08" zindex="3" storage="chara/kisaki/kisaki_08.png"]
[chara_layer name="kisaki" part="face" id="09" zindex="3" storage="chara/kisaki/kisaki_09.png"]
[chara_layer name="kisaki" part="face" id="12" zindex="3" storage="chara/kisaki/kisaki_12.png"]
[chara_layer name="kisaki" part="face" id="13" zindex="3" storage="chara/kisaki/kisaki_13.png"]
[chara_layer name="kisaki" part="face" id="14" zindex="3" storage="chara/kisaki/kisaki_14.png"]
[chara_layer name="kisaki" part="face" id="angry" zindex="3" storage="chara/kisaki/kisaki_angry.png"]
[chara_layer name="kisaki" part="face" id="default2" zindex="3" storage="chara/kisaki/kisaki_default2.png"]
[chara_layer name="kisaki" part="face" id="depressed" zindex="3" storage="chara/kisaki/kisaki_depressed.png"]
[chara_layer name="kisaki" part="face" id="embarrassed" zindex="3" storage="chara/kisaki/kisaki_embarrassed.png"]
[chara_layer name="kisaki" part="face" id="embarrassed2" zindex="3" storage="chara/kisaki/kisaki_embarrassed2.png"]
[chara_layer name="kisaki" part="face" id="eyeclose" zindex="3" storage="chara/kisaki/kisaki_eyeclose.png"]
[chara_layer name="kisaki" part="face" id="normal2" zindex="3" storage="chara/kisaki/kisaki_normal2.png"]
[chara_layer name="kisaki" part="face" id="respond2" zindex="3" storage="chara/kisaki/kisaki_respond2.png"]
[chara_layer name="kisaki" part="face" id="serious" zindex="3" storage="chara/kisaki/kisaki_serious.png"]
[chara_layer name="kisaki" part="face" id="serious2" zindex="3" storage="chara/kisaki/kisaki_serious2.png"]
[chara_layer name="kisaki" part="face" id="smile" zindex="3" storage="chara/kisaki/kisaki_smile.png"]
[chara_layer name="kisaki" part="face" id="smile2" zindex="3" storage="chara/kisaki/kisaki_smile2.png"]
[chara_layer name="kisaki" part="face" id="smile3" zindex="3" storage="chara/kisaki/kisaki_smile3.png"]
[chara_layer name="kisaki" part="face" id="surprised" zindex="3" storage="chara/kisaki/kisaki_surprised.png"]

[iscript]
    f.bukatsu = '对策委员会';
    f.serika_top = 61.55;
    f.serika_left = 24.30;
    f.serika_width = 919;
    f.serika_size = 1;
    f.serika_offset_L = 0.00;
    f.serika_offset_emo_L = 7.46;
    f.serika_offset_emo_T = 57.82;
    f.serika  = '芹香' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.serika_log = 'Serika';
[endscript]
;このゲームで登場するキャラクターを宣言
;serika
[chara_new name="serika" jname="&f.serika" storage="chara/serika/serika_body.png" logname="&f.serika_log"]
;キャラクターの表情登録
[chara_layer name="serika" part="halo" id="normal" zindex="1" storage="chara/serika/serika_halo0.png" frame_image="serika_halo1,serika_halo2,serika_halo3,serika_halo4,serika_halo5,serika_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="serika" part="body" id="body" zindex="2" storage="chara/serika/serika_body.png"]
[chara_layer name="serika" part="face" id="07" zindex="3" storage="chara/serika/serika_07.png"]
[chara_layer name="serika" part="face" id="08" zindex="3" storage="chara/serika/serika_08.png"]
[chara_layer name="serika" part="face" id="09" zindex="3" storage="chara/serika/serika_09.png"]
[chara_layer name="serika" part="face" id="10" zindex="3" storage="chara/serika/serika_10.png"]
[chara_layer name="serika" part="face" id="11" zindex="3" storage="chara/serika/serika_11.png"]
[chara_layer name="serika" part="face" id="12" zindex="3" storage="chara/serika/serika_12.png"]
[chara_layer name="serika" part="face" id="13" zindex="3" storage="chara/serika/serika_13.png"]
[chara_layer name="serika" part="face" id="default" zindex="3" storage="chara/serika/serika_default.png"]
[chara_layer name="serika" part="face" id="embarrassed" zindex="3" storage="chara/serika/serika_embarrassed.png"]
[chara_layer name="serika" part="face" id="eyeclose" zindex="3" storage="chara/serika/serika_eyeclose.png"]
[chara_layer name="serika" part="face" id="normal" zindex="3" storage="chara/serika/serika_normal.png"]
[chara_layer name="serika" part="face" id="respond" zindex="3" storage="chara/serika/serika_respond.png"]
[chara_layer name="serika" part="face" id="serious" zindex="3" storage="chara/serika/serika_serious.png"]
[chara_layer name="serika" part="face" id="shout" zindex="3" storage="chara/serika/serika_shout.png"]
[chara_layer name="serika" part="face" id="smile" zindex="3" storage="chara/serika/serika_smile.png"]
