; Generated by Character Editor
[chara_config ptext="chara_name_area" anim="true"]

[iscript]
    f.bukatsu = '超自然现象调查部';
    f.eimi_top = 55.13;
    f.eimi_left = 0.00;
    f.eimi_width = 692;
    f.eimi_size = 1;
    f.eimi_offset_L = 6.48;
    f.eimi_offset_emo_L = 76.22;
    f.eimi_offset_emo_T = 38.92;
    f.eimi  = '艾米' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.eimi_log = 'Eimi';
[endscript]
;このゲームで登場するキャラクターを宣言
;eimi
[chara_new name="eimi" jname="&f.eimi" storage="chara/eimi/eimi_body.png" logname="&f.eimi_log"]
;キャラクターの表情登録
[chara_layer name="eimi" part="halo" id="normal" zindex="1" storage="chara/eimi/eimi_halo0.png" frame_image="eimi_halo1,eimi_halo2,eimi_halo3,eimi_halo4,eimi_halo5,eimi_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="eimi" part="body" id="body" zindex="2" storage="chara/eimi/eimi_body.png"]
[chara_layer name="eimi" part="face" id="default" zindex="3" storage="chara/eimi/eimi_default.png"]
[chara_layer name="eimi" part="face" id="depressed" zindex="3" storage="chara/eimi/eimi_depressed.png"]
[chara_layer name="eimi" part="face" id="embarrass" zindex="3" storage="chara/eimi/eimi_embarrass.png"]
[chara_layer name="eimi" part="face" id="eyeclose" zindex="3" storage="chara/eimi/eimi_eyeclose.png"]
[chara_layer name="eimi" part="face" id="normal" zindex="3" storage="chara/eimi/eimi_normal.png"]
[chara_layer name="eimi" part="face" id="respond" zindex="3" storage="chara/eimi/eimi_respond.png"]
[chara_layer name="eimi" part="face" id="serious" zindex="3" storage="chara/eimi/eimi_serious.png"]
[chara_layer name="eimi" part="face" id="smile" zindex="3" storage="chara/eimi/eimi_smile.png"]

[iscript]
    f.bukatsu = '超自然现象调查部';
    f.himari_top = 74.60;
    f.himari_left = 0.00;
    f.himari_width = 834;
    f.himari_size = 1;
    f.himari_offset_L = 35.65;
    f.himari_offset_emo_L = 129.73;
    f.himari_offset_emo_T = 81.08;
    f.himari  = '日鞠' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.himari_log = 'Himari';
[endscript]
;このゲームで登場するキャラクターを宣言
;himari
[chara_new name="himari" jname="&f.himari" storage="chara/himari/himari_body.png" logname="&f.himari_log"]
;キャラクターの表情登録
[chara_layer name="himari" part="halo" id="normal" zindex="1" storage="chara/himari/himari_halo0.png" frame_image="himari_halo1,himari_halo2,himari_halo3,himari_halo4,himari_halo5,himari_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="himari" part="body" id="body" zindex="2" storage="chara/himari/himari_body.png"]
[chara_layer name="himari" part="face" id="default" zindex="3" storage="chara/himari/himari_default.png"]
[chara_layer name="himari" part="face" id="embarrass" zindex="3" storage="chara/himari/himari_embarrass.png"]
[chara_layer name="himari" part="face" id="eyeclose" zindex="3" storage="chara/himari/himari_eyeclose.png"]
[chara_layer name="himari" part="face" id="hologram" zindex="3" storage="chara/himari/himari_hologram.png"]
[chara_layer name="himari" part="face" id="normal" zindex="3" storage="chara/himari/himari_normal.png"]
[chara_layer name="himari" part="face" id="respond" zindex="3" storage="chara/himari/himari_respond.png"]
[chara_layer name="himari" part="face" id="respond2" zindex="3" storage="chara/himari/himari_respond2.png"]
[chara_layer name="himari" part="face" id="respond3" zindex="3" storage="chara/himari/himari_respond3.png"]
[chara_layer name="himari" part="face" id="sad" zindex="3" storage="chara/himari/himari_sad.png"]
[chara_layer name="himari" part="face" id="serious-" zindex="3" storage="chara/himari/himari_serious-.png"]
[chara_layer name="himari" part="face" id="serious" zindex="3" storage="chara/himari/himari_serious.png"]
[chara_layer name="himari" part="face" id="serious2" zindex="3" storage="chara/himari/himari_serious2.png"]
[chara_layer name="himari" part="face" id="smile" zindex="3" storage="chara/himari/himari_smile.png"]
[chara_layer name="himari" part="face" id="smile2" zindex="3" storage="chara/himari/himari_smile2.png"]
[chara_layer name="himari" part="face" id="smile3" zindex="3" storage="chara/himari/himari_smile3.png"]

[iscript]
    f.bukatsu = '梅花园';
    f.kokona_top = 112.25;
    f.kokona_left = 0.00;
    f.kokona_width = 693;
    f.kokona_size = 1;
    f.kokona_offset_L = -28.85;
    f.kokona_offset_emo_L = -64.14;
    f.kokona_offset_emo_T = 157.15;
    f.kokona  = '心奈' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.kokona_log = 'Kokona';
[endscript]
;このゲームで登場するキャラクターを宣言
;kokona
[chara_new name="kokona" jname="&f.kokona" storage="chara/kokona/kokona_body.png" logname="&f.kokona_log"]
;キャラクターの表情登録
[chara_layer name="kokona" part="halo" id="normal" zindex="1" storage="chara/kokona/kokona_halo0.png" frame_image="kokona_halo1,kokona_halo2,kokona_halo3,kokona_halo4,kokona_halo5,kokona_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="kokona" part="body" id="body" zindex="2" storage="chara/kokona/kokona_body.png"]
[chara_layer name="kokona" part="face" id="08" zindex="3" storage="chara/kokona/kokona_08.png"]
[chara_layer name="kokona" part="face" id="09" zindex="3" storage="chara/kokona/kokona_09.png"]
[chara_layer name="kokona" part="face" id="10" zindex="3" storage="chara/kokona/kokona_10.png"]
[chara_layer name="kokona" part="face" id="11" zindex="3" storage="chara/kokona/kokona_11.png"]
[chara_layer name="kokona" part="face" id="12" zindex="3" storage="chara/kokona/kokona_12.png"]
[chara_layer name="kokona" part="face" id="13" zindex="3" storage="chara/kokona/kokona_13.png"]
[chara_layer name="kokona" part="face" id="default" zindex="3" storage="chara/kokona/kokona_default.png"]
[chara_layer name="kokona" part="face" id="depressed" zindex="3" storage="chara/kokona/kokona_depressed.png"]
[chara_layer name="kokona" part="face" id="embarassed" zindex="3" storage="chara/kokona/kokona_embarassed.png"]
[chara_layer name="kokona" part="face" id="eyeclose" zindex="3" storage="chara/kokona/kokona_eyeclose.png"]
[chara_layer name="kokona" part="face" id="normal" zindex="3" storage="chara/kokona/kokona_normal.png"]
[chara_layer name="kokona" part="face" id="respond" zindex="3" storage="chara/kokona/kokona_respond.png"]
[chara_layer name="kokona" part="face" id="serious" zindex="3" storage="chara/kokona/kokona_serious.png"]
[chara_layer name="kokona" part="face" id="smile" zindex="3" storage="chara/kokona/kokona_smile.png"]
[chara_layer name="kokona" part="fronthair" id="fronthair" zindex="4" storage="chara/kokona/kokona_fronthair.png"]
