; Generated by Character Editor
[chara_config ptext="chara_name_area" anim="true"]

[iscript]
    f.bukatsu = '温泉开发部';
    f.kasumi_top = 0.00;
    f.kasumi_left = 0.00;
    f.kasumi_width = 1012;
    f.kasumi_size = 1;
    f.kasumi_offset_L = 0.00;
    f.kasumi_offset_emo_L = 71.35;
    f.kasumi_offset_emo_T = 95.68;
    f.kasumi  = '霞' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.kasumi_log = 'Kasumi';
[endscript]
;このゲームで登場するキャラクターを宣言
;kasumi
[chara_new name="kasumi" jname="&f.kasumi" storage="chara/kasumi/kasumi_body.png" logname="&f.kasumi_log"]
;キャラクターの表情登録
[chara_layer name="kasumi" part="halo" id="normal" zindex="1" storage="chara/kasumi/kasumi_halo0.png" frame_image="kasumi_halo1,kasumi_halo2,kasumi_halo3,kasumi_halo4,kasumi_halo5,kasumi_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="kasumi" part="body" id="body" zindex="2" storage="chara/kasumi/kasumi_body.png"]
[chara_layer name="kasumi" part="face" id="07" zindex="3" storage="chara/kasumi/kasumi_07.png"]
[chara_layer name="kasumi" part="face" id="08" zindex="3" storage="chara/kasumi/kasumi_08.png"]
[chara_layer name="kasumi" part="face" id="09" zindex="3" storage="chara/kasumi/kasumi_09.png"]
[chara_layer name="kasumi" part="face" id="10" zindex="3" storage="chara/kasumi/kasumi_10.png"]
[chara_layer name="kasumi" part="face" id="11" zindex="3" storage="chara/kasumi/kasumi_11.png"]
[chara_layer name="kasumi" part="face" id="12" zindex="3" storage="chara/kasumi/kasumi_12.png"]
[chara_layer name="kasumi" part="face" id="13" zindex="3" storage="chara/kasumi/kasumi_13.png"]
[chara_layer name="kasumi" part="face" id="14" zindex="3" storage="chara/kasumi/kasumi_14.png"]
[chara_layer name="kasumi" part="face" id="15" zindex="3" storage="chara/kasumi/kasumi_15.png"]
[chara_layer name="kasumi" part="face" id="default" zindex="3" storage="chara/kasumi/kasumi_default.png"]
[chara_layer name="kasumi" part="face" id="depressed" zindex="3" storage="chara/kasumi/kasumi_depressed.png"]
[chara_layer name="kasumi" part="face" id="embarrassed" zindex="3" storage="chara/kasumi/kasumi_embarrassed.png"]
[chara_layer name="kasumi" part="face" id="eyeclose" zindex="3" storage="chara/kasumi/kasumi_eyeclose.png"]
[chara_layer name="kasumi" part="face" id="normal" zindex="3" storage="chara/kasumi/kasumi_normal.png"]
[chara_layer name="kasumi" part="face" id="respond" zindex="3" storage="chara/kasumi/kasumi_respond.png"]
[chara_layer name="kasumi" part="face" id="serious" zindex="3" storage="chara/kasumi/kasumi_serious.png"]
[chara_layer name="kasumi" part="face" id="smile" zindex="3" storage="chara/kasumi/kasumi_smile.png"]
[chara_layer name="kasumi" part="fronthair" id="fronthair" zindex="4" storage="chara/kasumi/kasumi_fronthair.png"]

[iscript]
    f.bukatsu = '庆典运营管理部';
    f.pina_top = -24.05;
    f.pina_left = 0.00;
    f.pina_width = 1011;
    f.pina_size = 1;
    f.pina_offset_L = 64.12;
    f.pina_offset_emo_L = 72.16;
    f.pina_offset_emo_T = 62.54;
    f.pina  = '' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.pina_log = 'Pina';
[endscript]
;このゲームで登場するキャラクターを宣言
;pina
[chara_new name="pina" jname="&f.pina" storage="chara/pina/pina_body.png" logname="&f.pina_log"]
;キャラクターの表情登録
[chara_layer name="pina" part="halo" id="normal" zindex="1" storage="chara/pina/pina_halo0.png" frame_image="pina_halo1,pina_halo2,pina_halo3,pina_halo4,pina_halo5,pina_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="pina" part="body" id="body" zindex="2" storage="chara/pina/pina_body.png"]
[chara_layer name="pina" part="face" id="default" zindex="3" storage="chara/pina/pina_default.png"]
[chara_layer name="pina" part="face" id="depressed" zindex="3" storage="chara/pina/pina_depressed.png"]
[chara_layer name="pina" part="face" id="embarrass" zindex="3" storage="chara/pina/pina_embarrass.png"]
[chara_layer name="pina" part="face" id="eyeclose" zindex="3" storage="chara/pina/pina_eyeclose.png"]
[chara_layer name="pina" part="face" id="mischief" zindex="3" storage="chara/pina/pina_mischief.png"]
[chara_layer name="pina" part="face" id="normal" zindex="3" storage="chara/pina/pina_normal.png"]
[chara_layer name="pina" part="face" id="pity" zindex="3" storage="chara/pina/pina_pity.png"]
[chara_layer name="pina" part="face" id="respond" zindex="3" storage="chara/pina/pina_respond.png"]
[chara_layer name="pina" part="face" id="serious" zindex="3" storage="chara/pina/pina_serious.png"]
[chara_layer name="pina" part="face" id="smile" zindex="3" storage="chara/pina/pina_smile.png"]
[chara_layer name="pina" part="fronthair" id="fronthair" zindex="4" storage="chara/pina/pina_fronthair.png"]

[iscript]
    f.bukatsu = '炼丹研究会';
    f.saya_top = 139.51;
    f.saya_left = 0.00;
    f.saya_width = 572;
    f.saya_size = 1;
    f.saya_offset_L = 8.01;
    f.saya_offset_emo_L = 0.00;
    f.saya_offset_emo_T = 0.00;
    f.saya  = '纱绫' + ' ' + '<span class="bukatsu">' + f.bukatsu + '</span>';
    f.saya_log = 'Saya';
[endscript]
;このゲームで登場するキャラクターを宣言
;saya
[chara_new name="saya" jname="&f.saya" storage="chara/saya/saya_body.png" logname="&f.saya_log"]
;キャラクターの表情登録
[chara_layer name="saya" part="halo" id="normal" zindex="1" storage="chara/saya/saya_halo0.png" frame_image="saya_halo1,saya_halo2,saya_halo3,saya_halo4,saya_halo5,saya_halo6" frame_direction="alternate" frame_time="400,200,200,200,200,200,400" frame_loop="true"]
[chara_layer name="saya" part="body" id="body" zindex="2" storage="chara/saya/saya_body.png"]
[chara_layer name="saya" part="face" id="angry" zindex="3" storage="chara/saya/saya_angry.png"]
[chara_layer name="saya" part="face" id="default" zindex="3" storage="chara/saya/saya_default.png"]
[chara_layer name="saya" part="face" id="depressed" zindex="3" storage="chara/saya/saya_depressed.png"]
[chara_layer name="saya" part="face" id="embarrass" zindex="3" storage="chara/saya/saya_embarrass.png"]
[chara_layer name="saya" part="face" id="eyeclose" zindex="3" storage="chara/saya/saya_eyeclose.png"]
[chara_layer name="saya" part="face" id="nomal" zindex="3" storage="chara/saya/saya_nomal.png"]
[chara_layer name="saya" part="face" id="respond" zindex="3" storage="chara/saya/saya_respond.png"]
[chara_layer name="saya" part="face" id="serious" zindex="3" storage="chara/saya/saya_serious.png"]
[chara_layer name="saya" part="face" id="smile" zindex="3" storage="chara/saya/saya_smile.png"]
